dist: xenial
language: python
python:
  - '3.6'
before_script:
  - pip3 install .
script:
  - python3 -c "import paccmann"
  - training_paccmann -h
notifications:
  slack:
    secure: KaXOIz80a2w3O7/B/3vAE7cxR9GWbflaSO8m/ORKTitJt74mtoHRfWfv9YwcZ8VS/Vc/PGy31wtwEwFydU3sN72K5y7MdfpEeoARcX18JbV91AG7R4JwkPEdvhsIdD9hCrYbprzfH6g7q3po6UDL55LzjDSD7uZm2aezbMTDcCRZeTno3FSatVdcn5GiwRGNxedyt0NW3hdxI4aZA1zJUB24iWZsXCMf66vofUQ3kZYIoKCA2R8v+YRJHd/6H74JcAyYd9VoMD6PExT76oJX9s2pFtAb6Nru42E/9lovYos1AAhB7snfny5dOHibvp0B2dROeBo1nFQfzRwZceVRCshDHydhdGUTmtgqxgoB0KAQYLPomAEMgXb86tUP8ex/WAtd2svWrSimLBvgZ9R4nUGz4kI28aH3K477dbUK5IeEK8C8NbFv65QFZF13fFVdrdpFR8vWeRToe0bPDOduAF3DM1Cj+RG9HEnu+CIfJtw4W+7VxvMS1BOMOfvytlKV3zpwe4L4y4pyn1e5zdOpVe0Y/UPF0kykRiJmDbjmllz8crXUWv86pp3l04bzhD/L+Xerj6GItgCobAVzWEQYNg1m2OWR0sLKFOHWoCWyWoEhNLNeahH3pxQrUajw51zLl4Yzpm8NtspGNP+9F2pTnYca4XBjDusaLEBzb1ULO8E=
